Repository Liberty52/admin-page, pull requests merged in 2023-10, with the labels that each got.

#73 판매 상품 옵션 선택지 재고 수정 기능
  src/component/product/ProductIntroPanel.js
  src/component/product/ProductOptionDetailModal.js
  src/component/product/ProductOptionPanel.js
  src/component/product/styled/Product.js
  src/screen/product/Product.js
Labels: ✨ Feature

#75 [관리자] 상품 옵션 조회 관리 페이지 - 옵션 선택지 수량 표시
  src/component/product/ProductOptionDetail.js
  src/component/product/styled/Product.js
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#76 [LIB-71] 라이센스 추가, 조회
  package-lock.json
  package.json
  src/App.js
  src/axios/License.js
  src/component/common/side-nav/Config.js
  src/component/license/LicenseDialog.js
  src/component/license/LicenseItem.js
  src/constants/api.js
  src/constants/path.js
  src/screen/License.js
Labels: 📬 API, ✨ Feature, 🎨 Html&css, 🚧 WIP

#82 [LIB-77] Image Upscaler
  src/axios/Notice.js
  src/axios/Orders.js
  src/component/notice/NoticeDetail.js
  src/component/product/ProductOptionDetailModal.js
  src/component/product/ProductOptionModal.js
  src/screen/login/Login.js
Labels: 📬 API, ✨ Feature, 🎨 Html&css, 🖌 UI/UX

#89 [Issue#88] 리로드 없이 라이센스 조회
  src/component/license/LicenseDialog.js
  src/screen/License.js
Labels: 🚀 Performance

#95 [LIB-94] 이미지 업스케일링 결과 404
  src/screen/orders/OrderDetail.js
Labels: 🐞 BugFix

#107 [LIB-79] License Dialog 수정, 삭제
  package-lock.json
  src/axios/License.js
  src/component/license/LicenseDialog.js
  src/component/license/LicenseItem.js
  src/component/product/ProductIntroImageInput.js
  src/component/product/ProductIntroPanel.js
  src/constants/api.js
  src/constants/mode.js
  src/screen/License.js
Labels: 📬 API, ✨ Feature

#92 수정, 삭제
  src/axios/License.js
  src/component/license/LicenseDialog.js
  src/component/license/LicenseItem.js
  src/constants/api.js
  src/constants/mode.js
  src/screen/License.js
Labels: 📬 API, ✨ Feature

#100 [LIB-99] Question Dialog - 수정 모드 삭제 & Review Dialog - 기존에 존재하던 버그 수정
  src/component/question/QuestionDialog.js
  src/component/review/ReviewDialog.js
  src/constants/mode.js
Labels: 🐞 BugFix, 🎨 Html&css, 🔨 Refactor

#109 [ISSUE-108] [이미지 업스케일링] null exception
  src/screen/orders/OrderDetail.js
Labels: 🐞 BugFix

#111 [Issue#98] 리뷰 답글
  src/component/review/ReviewDialog.js
Labels: 🐞 BugFix

#118 [ISSUE-110] 업스케일링 중인 경우, 업스케일링 버튼 비활성화
  src/screen/orders/OrderDetail.js
Labels: 🚸 Usability, 🚀 Performance, ✨ Feature

#116 [LIB-100] 상품 추가, 조회
  package-lock.json
  src/axios/License.js
  src/component/license/LicenseDialog.js
  src/component/license/LicenseOption.js
  src/component/license/LicenseTable.js
  src/component/product/ProductItem.js
  src/constants/api.js
  src/screen/product/Product.js
  src/screen/product/ProductDetail.js
Labels: 📬 API, ✨ Feature

#123 [issue#120] 송장 등록 error
  src/component/license/LicenseDialog.js
  src/component/order/delivery/DeliveryDialog.js
Labels: 🐞 BugFix

#124 [Issue121] 국내/외 선택 시 택배사 동기화
  src/component/order/delivery/DeliveryDialog.js
Labels: 🐞 BugFix

#125 [LIB-122] 상품 소개 CRUD
  src/App.css
  src/axios/Product.js
  src/component/customer/CustomerTable.js
  src/component/notice/NoticeEditor.js
  src/component/notice/NoticeTable.js
  src/component/product/ProductIntroEditor.js
  src/component/product/ProductIntroImageInput.css
  src/component/product/ProductIntroImageInput.js
  src/component/product/ProductIntroPanel.js
  src/component/product/ProductOption.js
  src/component/product/ProductOptionDetail.js
  src/component/product/ProductOptionPanel.js
  src/component/product/ProductTab.js
  src/component/product/styled/ProductIntroEditorComponent.js
  src/component/question/QuestionTable.js
  src/constants/api.js
  src/screen/product/Product.js
  src/screen/product/ProductDetail.js
Labels: 📬 API, ✨ Feature, 🎨 Html&css, 🔨 Refactor
