Repository Liberty52/admin-page, pull requests merged in 2023-11, with the labels that each got.

#128 [feat] Product Delivery Option Get/Add/Update
  src/axios/Product.js
  src/component/product/ProductDeliveryOptionPanel.js
  src/component/product/ProductTab.js
  src/constants/api.js
  src/constants/message.js
Labels: ✨ Feature

#138 [ISSUE-137] npm 종속성으로 인한 build fail 문제
  .github/workflows/ci.yaml
  multistage.Dockerfile
Labels: 🐞 BugFix, 🌏 Deploy

#131 Issue#127
  src/component/product/ProductDeliveryOptionPanel.js
Labels: 🐞 BugFix, 🚧 WIP

#139 [feat] 리뷰 반영 및 택배사 동적화
  src/component/product/ProductDeliveryOptionPanel.js
  src/constants/message.js
Labels: ✨ Feature

#140 [LIB-127]라이선스 옵션 CRU
  package-lock.json
  src/axios/License.js
  src/component/license/LicenseDialog.js
  src/component/product/LicenseOptionDetail.js
  src/component/product/LicenseOptionDetailModal.js
  src/component/product/LicenseOptionModal.js
  src/component/product/LicenseOptionPanel.js
  src/component/product/LicenseProductOption.js
  src/component/product/ProductTab.js
  src/component/product/styled/Product.js
  src/constants/api.js
Labels: 📬 API, ✨ Feature

#141 [관리자] License Table Update기능
  package-lock.json
  src/axios/Product.js
  src/component/license/LicenseTable.js
  src/constants/api.js
  src/screen/product/ProductDetail.js
Labels: ✨ Feature

#145 [ISSUE-142]라이선스 FIX
  package-lock.json
  src/axios/License.js
  src/component/license/LicenseDialog.js
  src/component/license/LicenseOption.js
  src/component/license/LicenseTable.js
  src/component/product/LicenseOptionDetail.js
  src/component/product/LicenseOptionDetailModal.js
  src/component/product/LicenseOptionModal.js
  src/component/product/LicenseOptionPanel.js
  src/component/product/LicenseProductOption.js
  src/component/product/ProductOption.js
  src/component/product/ProductOptionDetail.js
  src/component/product/ProductTab.js
  src/constants/api.js
  src/screen/product/ProductDetail.js
Labels: 🚸 Usability, 🚧 WIP

#150 [관리자] [상품 소개] CRUD html 코드로
  src/component/product/EditorPreview.js
  src/component/product/ProductIntroEditor.js
  src/screen/product/ProductDetail.js
Labels: 🚸 Usability, ✨ Feature

#151 [LIB-148] 총 매출액 조회
  package-lock.json
  src/App.js
  src/axios/Sales.js
  src/component/common/Input.css
  src/component/common/side-nav/Config.js
  src/component/license/LicenseDialog.js
  src/component/license/LicenseOption.js
  src/component/product/LicenseOptionDetailModal.js
  src/component/product/styled/Product.js
  src/component/sales/OverviewBudget.js
  src/component/sales/OverviewLatestOrders.js
  src/component/sales/OverviewLatestProducts.js
  src/component/sales/OverviewSales.js
  src/component/sales/OverviewTasksProgress.js
  src/component/sales/OverviewTotalCustomers.js
  src/component/sales/OverviewTotalProfit.js
  src/component/sales/OverviewTraffic.js
  src/component/sales/SalesDialog.js
  src/constants/api.js
  src/constants/path.js
  src/screen/Sales.js
  src/screen/product/ProductDetail.js
Labels: 📬 API, 🔨 Refactor

#156 feat:관리자는 이미지 에디터 미리보기 효과 관리한다
  package-lock.json
  package.json
  src/App.js
  src/api/ImageEditorSetting/PreviewEffect/index.ts
  src/api/PresignedUrl.ts
  src/component/common/side-nav/Config.js
  src/constants/path.js
  src/screen/image-editor/components/PreviewEffectItem/AddPreviewEffectItemCard.styled.tsx
  src/screen/image-editor/components/PreviewEffectItem/AddPreviewEffectItemCard.tsx
  src/screen/image-editor/components/PreviewEffectItem/PreviewEffectItem.styled.tsx
  src/screen/image-editor/components/PreviewEffectItem/PreviewEffectItem.tsx
  src/screen/image-editor/components/PreviewEffectList/PreviewEffectList.styled.tsx
  src/screen/image-editor/components/PreviewEffectList/PreviewEffectList.tsx
  src/screen/image-editor/components/TabList/TabList.tsx
  src/screen/image-editor/page.styled.tsx
  src/screen/image-editor/page.tsx
  src/screen/image-editor/preview-effects/[previewEffectId]/page.styled.tsx
  src/screen/image-editor/preview-effects/[previewEffectId]/page.tsx
  src/types/ImageEditorSetting/client.ts
  src/types/ImageEditorSetting/enum.ts
  src/types/ImageEditorSetting/remote.ts
Labels: ✨ Feature
