Repository Liberty52/admin-page, pull requests merged in 2023-09, with the labels that each got.

#63 [LIB-62] 상품 소개 관리 화면
  src/App.js
  src/axios/Product.js
  src/component/common/side-nav/SideNav.js
  src/component/product/ProductIntroImageInput.css
  src/component/product/ProductIntroImageInput.js
  src/component/product/ProductIntroPanel.js
  src/component/product/ProductOptionPanel.js
  src/component/product/ProductTab.js
  src/component/product/styled/Product.js
  src/constants/api.js
  src/constants/path.js
  src/image/preview-example.png
  src/screen/product/Product.js
  src/screen/product/ProductDetail.js
Labels: enhancement

#67 [LIB-65] 상품 소개 관리 수정 (do not merge)
  src/axios/Product.js
  src/component/product/ProductIntroPanel.js
Labels: 📬 API, ✨ Feature, 🚧 WIP

#68 [LIB-64] 상품 소개 조회
  src/axios/Product.js
  src/component/product/ProductIntroImageInput.js
  src/component/product/ProductIntroPanel.js
  src/component/product/ProductTab.js
  src/image/preview-example.png
  src/screen/product/ProductDetail.js
Labels: 📬 API, 🐞 BugFix, ✨ Feature

#70 [hotfix] 상품 소개 관리 수정 오류 해결
  src/axios/Product.js
Labels: 🐞 BugFix
